### ISSUE TITLE
Dual licensing

### ISSUE THREAD

**Issue by davwheat** [anisotropi4/woodpecker#4]
I'm looking into using the TIPLOC data compiled at https://github.com/oweno-tfwm/YA_Tiploc_List, which uses some data from `woodpecker`.

While most of its data sources use OGL3 or CC-BY(-SA) licenses, woodpecker uses Apache 2.0.

I was wondering whether you'd be open to dual licensing the data in the repo under CC-BY 4.0 or CC-BY-SA 4.0 to allow the STANOX data to be combined with these other data sources more easily.

My plan for the data is to use the combined data from YATIPLOCL and snap those locations back to the latest Network Rail network GIS data and republish this as (yet another) copyleft dataset.

Thanks in advance, and please let me know if you have any questions.

**Comment by anisotropi4** [comment]
Good morning David, apologies for the delay in getting to this. I'll update the license now and make the data output CC-BY-SA. 

If that works, I'll close the issue.

**Comment by anisotropi4** [comment]
I have added a link in the `README.md` that indicates data is covered by the `CC-BY-SA 4.0`. I can't find a text copy of the corresponding `CC-BY` license so this is a link, but if there is a copy I'll update the `LICENSE` file or somesuch.

**Comment by davwheat** [comment]
I think I found a plaintext deed here: https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt

**Comment by anisotropi4** [comment]
With your agreement as the data attribution license is now CC-BY-SA 4.0, I would propose closing the this. Unlike the Apache license, I can't see where I would put or update the CC-BY-SA license in this case.

**Comment by davwheat** [comment]
Yeah, perfectly happy to close this now. Thanks for this. :)
